services:
  - type: web
    name: cv-django-app
    runtime: python3
    buildCommand: "./build.sh"
    startCommand: "gunicorn config.wsgi:application --bind 0.0.0.0:$PORT --workers 2 --threads 2 --timeout 30"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - key: ALLOWED_HOSTS
        fromService:
          type: web
          name: cv-django-app
          property: host
